In [58]:
import torch
x = torch.randn(100,4)
x = x.reshape(10,-1,4)
print(x.shape)
probabilities = torch.softmax(x, dim=1).view(-1, 4)
# 计算每个样本概率总和并获取最大概率的位置索引
print(probabilities.shape)
sum_probs = torch.sum(probabilities, dim=0)
print(sum_probs)
max_prob_idx = torch.argmax(sum_probs, dim=0)
max_prob_idx.item()

torch.Size([10, 10, 4])
torch.Size([100, 4])
tensor([10.0000, 10.0000, 10.0000, 10.0000])


2

In [19]:
import torch
from torch.nn import functional
a = torch.randn(10,2)

lin = torch.nn.Linear(2,5,False)
for param in lin.parameters():
    print(param)
# print(lin.named_modules())
print(lin(a))
# print(torch.mul(a,(lin.weight).T))
functional.linear(a,lin.weight)

Parameter containing:
tensor([[-0.1469,  0.3493],
        [-0.4337, -0.0356],
        [ 0.4448,  0.5414],
        [ 0.4740,  0.1614],
        [ 0.0416,  0.6871]], requires_grad=True)
tensor([[-0.6293, -0.5653, -0.0320,  0.4695, -0.7742],
        [ 0.6409,  0.1415,  0.6835,  0.0464,  1.1084],
        [ 0.1430,  0.0667,  0.0998, -0.0321,  0.2214],
        [-0.3449, -0.1441, -0.2661,  0.0571, -0.5465],
        [ 0.5404, -0.2372,  1.1107,  0.4697,  1.1973],
        [ 0.2690,  0.4527, -0.3027, -0.4556,  0.1754],
        [-0.3904,  0.3851, -1.1228, -0.5976, -1.0224],
        [ 0.1039,  0.1040, -0.0106, -0.0903,  0.1200],
        [ 0.0334,  0.1447, -0.1702, -0.1635, -0.0434],
        [ 0.4104, -0.1787,  0.8413,  0.3550,  0.9082]], grad_fn=<MmBackward0>)


tensor([[-0.6293, -0.5653, -0.0320,  0.4695, -0.7742],
        [ 0.6409,  0.1415,  0.6835,  0.0464,  1.1084],
        [ 0.1430,  0.0667,  0.0998, -0.0321,  0.2214],
        [-0.3449, -0.1441, -0.2661,  0.0571, -0.5465],
        [ 0.5404, -0.2372,  1.1107,  0.4697,  1.1973],
        [ 0.2690,  0.4527, -0.3027, -0.4556,  0.1754],
        [-0.3904,  0.3851, -1.1228, -0.5976, -1.0224],
        [ 0.1039,  0.1040, -0.0106, -0.0903,  0.1200],
        [ 0.0334,  0.1447, -0.1702, -0.1635, -0.0434],
        [ 0.4104, -0.1787,  0.8413,  0.3550,  0.9082]], grad_fn=<MmBackward0>)